"""
Audit PDF Generator for Vi Cloud Service Fulfillment.
Pure Python, no LLM. Takes Intake + Policy results, produces compliance PDF.
"""

import os
import uuid
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm, mm
from reportlab.platypus import (
    PageBreak, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle,
)

from agents.common.schemas import IntakeResult, PolicyResult

VI_RED = colors.HexColor("#E60000")
VI_DARK = colors.HexColor("#1A1A1A")
GREY_LIGHT = colors.HexColor("#F4F4F4")
GREY_BORDER = colors.HexColor("#CCCCCC")
PASS_GREEN = colors.HexColor("#1B8A4D")
WARN_AMBER = colors.HexColor("#E68A00")
FAIL_RED = colors.HexColor("#C0202C")


@dataclass
class AuditData:
    workflow_id: str
    customer_name: str
    intake: IntakeResult
    policy: PolicyResult
    generated_at: datetime
    approval_signoff: Optional[str] = None
    deployment_status: Optional[str] = None


def _header_footer(canvas, doc):
    canvas.saveState()

    # Red header bar
    canvas.setFillColor(VI_RED)
    canvas.rect(0, A4[1] - 1.5 * cm, A4[0], 1.5 * cm, fill=1, stroke=0)
    canvas.setFillColor(colors.white)
    canvas.setFont("Helvetica-Bold", 14)
    canvas.drawString(1.5 * cm, A4[1] - 1.0 * cm, "Vi  |  Cloud Service Fulfillment")
    canvas.setFont("Helvetica", 9)
    canvas.drawRightString(
        A4[0] - 1.5 * cm, A4[1] - 1.0 * cm,
        "Agentic AI Platform - Audit Report",
    )

    # Footer
    canvas.setFillColor(VI_DARK)
    canvas.setFont("Helvetica", 8)
    canvas.drawString(
        1.5 * cm, 1.0 * cm,
        f"Generated by Azkashine AI Platform - Page {doc.page}",
    )
    canvas.drawRightString(
        A4[0] - 1.5 * cm, 1.0 * cm,
        "Confidential - Internal Use Only",
    )

    canvas.restoreState()


def _styles():
    s = getSampleStyleSheet()
    s.add(ParagraphStyle(
        name="ViTitle",
        fontName="Helvetica-Bold",
        fontSize=20,
        textColor=VI_RED,
        spaceAfter=12,
        alignment=TA_LEFT,
    ))
    s.add(ParagraphStyle(
        name="ViSection",
        fontName="Helvetica-Bold",
        fontSize=13,
        textColor=VI_RED,
        spaceBefore=18,
        spaceAfter=8,
        borderPadding=4,
    ))
    s.add(ParagraphStyle(
        name="ViBody",
        fontName="Helvetica",
        fontSize=10,
        leading=14,
        textColor=VI_DARK,
        spaceAfter=6,
    ))
    s.add(ParagraphStyle(
        name="ViLabel",
        fontName="Helvetica-Bold",
        fontSize=10,
        textColor=VI_DARK,
    ))
    s.add(ParagraphStyle(
        name="ViMono",
        fontName="Courier",
        fontSize=9,
        leading=12,
        textColor=VI_DARK,
        backColor=GREY_LIGHT,
        borderPadding=8,
    ))
    return s


def _kv_table(rows: list[tuple[str, str]], col_widths=None) -> Table:
    cell_style = ParagraphStyle(
        name="CellWrap",
        fontName="Helvetica",
        fontSize=10,
        leading=13,
        textColor=VI_DARK,
    )
    data = [[k, Paragraph(str(v), cell_style)] for k, v in rows]
    table = Table(
        data,
        colWidths=col_widths or [5 * cm, 12 * cm],
    )
    table.setStyle(TableStyle([
        ("FONT", (0, 0), (0, -1), "Helvetica-Bold", 10),
        ("TEXTCOLOR", (0, 0), (-1, -1), VI_DARK),
        ("BACKGROUND", (0, 0), (0, -1), GREY_LIGHT),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("INNERGRID", (0, 0), (-1, -1), 0.5, GREY_BORDER),
        ("BOX", (0, 0), (-1, -1), 0.5, GREY_BORDER),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))
    return table


def _status_color(status: str):
    return {
        "pass": PASS_GREEN,
        "warn": WARN_AMBER,
        "fail": FAIL_RED,
    }.get(status, VI_DARK)


def _checks_table(checks) -> Table:
    cell_style = ParagraphStyle(
        name="ChkCell",
        fontName="Helvetica",
        fontSize=9,
        leading=11,
        textColor=VI_DARK,
    )
    header = ["#", "Check", "Status", "Details", "Policy Ref"]
    data = [header]
    for i, c in enumerate(checks, 1):
        data.append([
            str(i),
            Paragraph(c.name, cell_style),
            c.status.upper(),
            Paragraph(c.details, cell_style),
            Paragraph(c.policy_ref or "-", cell_style),
        ])

    table = Table(
        data,
        colWidths=[0.7 * cm, 3.2 * cm, 1.5 * cm, 7.6 * cm, 3.0 * cm],
        repeatRows=1,
    )
    style = TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), VI_RED),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONT", (0, 0), (-1, 0), "Helvetica-Bold", 10),
        ("FONT", (0, 1), (-1, -1), "Helvetica", 9),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("INNERGRID", (0, 0), (-1, -1), 0.4, GREY_BORDER),
        ("BOX", (0, 0), (-1, -1), 0.4, GREY_BORDER),
        ("LEFTPADDING", (0, 0), (-1, -1), 5),
        ("RIGHTPADDING", (0, 0), (-1, -1), 5),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ])
    for i, c in enumerate(checks, 1):
        style.add("TEXTCOLOR", (2, i), (2, i), _status_color(c.status))
        style.add("FONT", (2, i), (2, i), "Helvetica-Bold", 9)
        if i % 2 == 0:
            style.add("BACKGROUND", (0, i), (-1, i), GREY_LIGHT)
    table.setStyle(style)
    return table


def _sites_table(intake: IntakeResult, policy: PolicyResult) -> Table:
    from agents.policy.rules import estimate_site_cost
    header = ["#", "City", "State", "Bandwidth (Mbps)", "Monthly Cost (Rs)"]
    data = [header]
    for i, s in enumerate(intake.sites, 1):
        cost = estimate_site_cost(
            s, intake.connectivity_type, intake.compliance_tier,
        )
        data.append([
            str(i),
            s.city,
            s.state or "-",
            str(s.bandwidth_mbps),
            f"{cost:,}",
        ])

    table = Table(
        data,
        colWidths=[0.8 * cm, 3.5 * cm, 3.5 * cm, 3.8 * cm, 4.4 * cm],
        repeatRows=1,
    )
    style = TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), VI_RED),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONT", (0, 0), (-1, 0), "Helvetica-Bold", 10),
        ("FONT", (0, 1), (-1, -1), "Helvetica", 9),
        ("ALIGN", (3, 1), (4, -1), "RIGHT"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("INNERGRID", (0, 0), (-1, -1), 0.4, GREY_BORDER),
        ("BOX", (0, 0), (-1, -1), 0.4, GREY_BORDER),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ])
    for i in range(1, len(data)):
        if i % 2 == 0:
            style.add("BACKGROUND", (0, i), (-1, i), GREY_LIGHT)
    table.setStyle(style)
    return table


def generate_audit_pdf(data: AuditData, output_path: str) -> str:
    """Generate the audit PDF. Returns the absolute output path."""
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)

    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        topMargin=2.5 * cm,
        bottomMargin=2 * cm,
        leftMargin=1.5 * cm,
        rightMargin=1.5 * cm,
        title=f"Vi Audit Report - {data.workflow_id}",
        author="Azkashine Agentic AI Platform",
    )

    styles = _styles()
    body = styles["ViBody"]
    section = styles["ViSection"]
    story = []

    # ---- Cover block ----
    story.append(Paragraph("Cloud Service Fulfillment Audit", styles["ViTitle"]))
    story.append(Paragraph(
        "Agentic AI-driven onboarding - automated compliance attestation",
        body,
    ))
    story.append(Spacer(1, 0.4 * cm))

    cover_rows = [
        ("Workflow ID", data.workflow_id),
        ("Customer", data.customer_name),
        ("Generated", data.generated_at.strftime("%Y-%m-%d %H:%M:%S %Z")),
        ("Overall Decision", data.policy.overall_status.upper().replace("_", " ")),
        ("Approval Level", data.policy.approval_level_required.upper()),
        ("Estimated Monthly Cost",
         f"Rs {data.policy.estimated_cost_inr_monthly:,}"),
        ("Estimated Annual Cost",
         f"Rs {data.policy.estimated_cost_inr_monthly * 12:,}"),
        ("Sites Requested", str(data.intake.site_count)),
        ("Connectivity Type", data.intake.connectivity_type),
        ("Compliance Tier", data.intake.compliance_tier),
        ("Deadline", data.intake.deadline or "Not specified"),
    ]
    story.append(_kv_table(cover_rows))

    # ---- Executive Summary ----
    story.append(Paragraph("Executive Summary", section))
    story.append(Paragraph(data.policy.summary, body))

    # ---- Original Request ----
    story.append(Paragraph("Original Customer Request", section))
    story.append(Paragraph(
        f"Captured verbatim from intake portal:",
        body,
    ))
    story.append(Spacer(1, 0.2 * cm))
    story.append(Paragraph(data.intake.raw_request, styles["ViMono"]))
    story.append(Spacer(1, 0.3 * cm))
    story.append(Paragraph(
        f"<b>Intake Confidence:</b> {data.intake.confidence:.2%} - "
        f"{'No clarification needed' if not data.intake.needs_clarification else 'Clarification requested'}",
        body,
    ))

    # ---- Compliance Validation ----
    story.append(PageBreak())
    story.append(Paragraph("Compliance Validation", section))
    story.append(Paragraph(
        f"Total of {len(data.policy.checks)} policy checks were executed automatically. "
        f"Each check references the relevant Vi internal policy.",
        body,
    ))
    story.append(Spacer(1, 0.3 * cm))
    story.append(_checks_table(data.policy.checks))

    # ---- Sites Inventory ----
    if data.intake.sites:
        story.append(Paragraph("Sites Inventory", section))
        story.append(_sites_table(data.intake, data.policy))

    # ---- Approval Chain ----
    story.append(Paragraph("Approval Chain", section))
    approval_rows = [
        ("Required Level", data.policy.approval_level_required.upper()),
        ("Status", data.approval_signoff or "PENDING"),
        ("Cost Threshold Breach",
         "Yes" if any("Cost Threshold" in c.name and c.status == "warn"
                      for c in data.policy.checks) else "No"),
        ("BFSI Review Required",
         "Yes" if data.intake.compliance_tier == "BFSI_equivalent" else "No"),
    ]
    story.append(_kv_table(approval_rows))

    # ---- Signature ----
    story.append(Paragraph("Signatures and Attestation", section))
    sig_rows = [
        ("Platform Version", "Azkashine Agentic AI v1.0"),
        ("AI Attestation",
         "All checks executed by deterministic policy engine; "
         "extraction by LLM with structured-output validation"),
        ("Cryptographic Reference", f"workflow:{data.workflow_id}"),
        ("Generated At", data.generated_at.strftime("%Y-%m-%d %H:%M:%S %Z")),
    ]
    story.append(_kv_table(sig_rows))

    doc.build(story, onFirstPage=_header_footer, onLaterPages=_header_footer)
    return os.path.abspath(output_path)


def build_audit(
    intake: IntakeResult,
    policy: PolicyResult,
    customer_name: str = "Unnamed Customer",
    output_dir: str = "audits",
    approval_signoff: Optional[str] = None,
) -> str:
    """Convenience entry point - returns generated PDF path."""
    workflow_id = f"wf-{uuid.uuid4().hex[:12]}"
    filename = f"{workflow_id}.pdf"
    output_path = os.path.join(output_dir, filename)

    data = AuditData(
        workflow_id=workflow_id,
        customer_name=customer_name,
        intake=intake,
        policy=policy,
        generated_at=datetime.now(timezone.utc),
        approval_signoff=approval_signoff,
    )
    return generate_audit_pdf(data, output_path)
